name: Lint and Format
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: write # for checkout
  pull-requests: write # for comments

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16.10.0'
      - name: Install Dependencies
        run: |
          node --version
          npm ci --production
      - name: Run format fix script
        run: npm run format
      - name: Run format check
        run: npm run check
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
